//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MeetingRoom
    {
        public MeetingRoom()
        {
            this.Reservations = new HashSet<Reservation>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public string Location { get; set; }
    
        public virtual ICollection<Reservation> Reservations { get; set; }
    }
}
