//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestProj.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MeetingRoomsDBEntities : DbContext
    {
        public MeetingRoomsDBEntities()
            : base("name=MeetingRoomsDBEntities")
        {
        }
    
        public virtual DbSet<MeetingRoom> MeetingRooms { get; set; }
        public virtual DbSet<Reservation> Reservations { get; set; }
    }
}
