//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class FriendRequest
    {
        public int Id { get; set; }
        public string FromId { get; set; }
        public string ToId { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
